---

- name: Enable copr
  shell: dnf copr enable -y jdoss/wireguard
  become: true

- name: Install wireguard
  dnf:
    name: ["wireguard-tools{{wireguard_version}}", "wireguard-dkms{{wireguard_version}}"]
  become: true
  allow_downgrade: true
