#Deploys Graylog collector to log system metrics, not run by default
- name: Install the Collector Sidecar RPM
  yum:
    name: "{{sidecar_rpm}}"
    state: latest
  become: true
  when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install the Collector Sidecar DEB
  apt:
    name: "{{sidecar_deb}}"
    state: latest
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Fail on nonsystemd systems
  fail:
    msg: "No support for non systemd services, please add support for your init system!"
  when: "ansible_service_mgr != 'systemd'"

- name: Setup Sidecar service
  shell: "graylog-collector-sidecar -service install"
  become: true
  ignore_errors: true

- name: Create config folder
  file:
    path: /etc/graylog/graylog-sidecar/
    state: directory
  become: true

- name: Template sidecar config
  template:
    src: collector_sidecar.yml.j2
    dest: /etc/graylog/collector-sidecar/collector_sidecar.yml
  become: true

- name: Set Collector-sidecar to run on startup
  systemd:
    daemon_reload: yes
    name: collector-sidecar
    state: restarted
    enabled: yes
  become: true

- name: Wait for Quick crashes
  pause:
    seconds: 30

- name: Check if collector-sidecar is running
  command: systemctl status collector-sidecar
  ignore_errors: yes
  changed_when: false
  register: service_collector_sidecar_status

- name: Report status of collector_sidecar
  fail:
    msg: |
      Service graylog-sidecar is not running.
      Output of `systemctl status collector-sidecar`:
      {{ service_collector_sidecar_status.stdout }}
      {{ service_collector_sidecar_status.stderr }}
  when: service_collector_sidecar_status is failed

- name: Close rsyslog port on wg_exit only
  iptables:
    chain: INPUT
    destination_port: 514
    in_interface: "wg_exit"
    protocol: udp
    ip_version: "{{item}}"
    jump: REJECT
    ctstate: NEW
  become: true
  with_items:
    - ipv4
    - ipv6

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  become: true
  ignore_errors: true

- name: Check iptables status
  service:
    name: "{{item}}"
    state: started
    enabled: yes
  become: true
  with_items:
    - iptables
    - ip6tables
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora'

- name: save iptables rules
  shell: "service {{item}} save"
  become: true
  with_items:
    - iptables
    - ip6tables
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora'

- name: save iptables rules
  shell: "{{item}}"
  become: true
  with_items:
    - "iptables-save > /etc/iptables/rules.v4"
    - "ip6tables-save > /etc/iptables/rules.v6"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted
    enabled: true
  become: true

- name: Exit Journalctl configs to prevent rate limiting
  lineinfile:
    path: /etc/systemd/journald.conf
    state: present
    line: "{{item}}"
    insertafter: '^[Journal]'
  with_items:
   - "RateLimitInterval=1s"
   - "RateLimitBurst=1000000"

- name: Restart systemd-journald
  service:
    name: systemd-journald
    state: restarted
    enabled: true
  become: true
